# Generated by Django 3.2.5 on 2021-07-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='short_code',
            field=models.CharField(default='ABC', max_length=3),
            preserve_default=False,
        ),
    ]
